# Generated by Django 5.1.5 on 2025-04-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_code',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
