# Generated by Django 5.2 on 2025-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
