# Generated by Django 5.0 on 2025-04-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.location"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
