# Generated by Django 5.0 on 2025-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_location_created_at_alter_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
