# Generated by Django 5.0 on 2025-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_event_location_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="custom_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
